# Generated by Django 6.0.2 on 2026-03-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_unique_doctor_appointment_time_and_more'),
        ('doctors', '0002_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appointments.appointment')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Doctor who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
            ],
        ),
    ]
